name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${Lander39}
          password: ${Fi*-*9afNzBi-Rs}

      - name: Build Docker image
        run: docker build -t my-node-app:latest .

      - name: Push Docker image
        run: docker push my-node-app:latest
