name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Wordt uitgevoerd bij push naar de main branch
  workflow_dispatch:  # Je kunt het ook handmatig starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if GHCR_PAT secret is available
        run: |
          if [ -z "${{ secrets.GHCR_PAT }}" ]; then
            echo "❌ ERROR: GHCR_PAT secret is missing!"
            exit 1
          fi

      - name: Log in to GitHub Container Registry with PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Lander03
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/lander03/projectitlandscape:latest .

      - name: Push Docker image
        run: docker push ghcr.io/lander03/projectitlandscape:latest
